# Generated by Django 4.0.3 on 2022-03-31 14:59

from django.db import migrations, models
import django_extensions.db.fields
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='이메일')),
                ('password', encrypted_model_fields.fields.EncryptedCharField(verbose_name='비밀번호')),
                ('nick_name', models.CharField(max_length=10, verbose_name='닉네임')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
